# Generated by Django 3.2.3 on 2021-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('discord_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('account_id', models.BigIntegerField()),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
    ]
