# Generated by Django 3.2.3 on 2021-05-31 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdiscordcauth', '0002_auto_20210531_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackmaniauser',
            name='id',
        ),
        migrations.AlterField(
            model_name='trackmaniauser',
            name='account_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
