# Generated by Django 3.2.3 on 2021-06-01 19:04

from django.db import migrations, models
import tmdiscordcauth.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tmdiscordcauth', '0004_alter_discorduser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trackmaniauser',
            managers=[
                ('objects', tmdiscordcauth.managers.TrackmaniaUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='trackmaniauser',
            name='account_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
